name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        run: |
          bash ./deploy_cloud_run.sh
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGISTRY_REGION: ${{ secrets.GCP_REGISTRY_REGION }}
          RUN_REGION: ${{ secrets.GCP_RUN_REGION }}
          SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
