name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.GCP_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REGISTRY_REPO }}/${{ secrets.GCP_SERVICE_NAME }}:latest
      RUN_REGION: ${{ secrets.GCP_RUN_REGION }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker "${{ secrets.GCP_REGISTRY_REGION }}-docker.pkg.dev" --quiet
      - name: Build Docker image
        run: docker build -t "$IMAGE_NAME" ./dev-web
      - name: Push Docker image
        run: docker push "$IMAGE_NAME"
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_NAME" \
            --platform=managed \
            --region "$RUN_REGION" \
            --allow-unauthenticated
