name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sdk:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

  build-push-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [sdk]

    permissions:
      contents: read
      id-token: write

    env:
      GCP_PROJECT_ID:      ${{ vars.GCP_PROJECT_ID }}
      GCP_REGISTRY_REGION: ${{ vars.GCP_REGISTRY_REGION }}
      GCP_REGISTRY_REPO:   ${{ vars.GCP_REGISTRY_REPO }}
      GCP_SERVICE_NAME:    ${{ vars.GCP_SERVICE_NAME }}
      GCP_RUN_REGION:      ${{ vars.GCP_RUN_REGION }}
      IMAGE_TAG:           ${{ github.sha }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        id: checkout-code

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: auth-gcloud
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WID_POOL }}
          service_account: ${{ env.GCP_SA_EMAIL }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker \
            "${{ env.GCP_REGISTRY_REGION }}-docker.pkg.dev" --quiet

      - name: Build & Push Docker image
        run: |
          IMAGE_URI="${{ env.GCP_REGISTRY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REGISTRY_REPO }}/${{ env.GCP_SERVICE_NAME }}:$IMAGE_TAG"
          docker build -t "$IMAGE_URI" ./dev-web
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service:               ${{ env.GCP_SERVICE_NAME }}
          image:                 ${{ env.GCP_REGISTRY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REGISTRY_REPO }}/${{ env.GCP_SERVICE_NAME }}:$IMAGE_TAG
          region:                ${{ env.GCP_RUN_REGION }}
          allow_unauthenticated: true
